// Client-safe definitions for the final objective assessment.
// The answer key intentionally lives in lib/assessment-scoring.ts (server only).

export const OBJECTIVE_ASSESSMENT_VERSION = "objective_v1" as const;

export const OBJECTIVE_QUESTION_IDS = [
  "q1",
  "q2",
  "q3",
  "q4",
  "q5",
  "q6",
  "q7",
  "q8",
  "q9",
  "q10",
  "q11",
  "q12",
  "q13",
  "q14",
  "q15",
  "q16",
  "q17",
  "q18",
  "q19",
  "q20",
] as const;

export type ObjectiveQuestionId = (typeof OBJECTIVE_QUESTION_IDS)[number];
export type ObjectiveAnswerColumn = `${ObjectiveQuestionId}_answer`;

export const ANSWER_LETTERS = ["A", "B", "C", "D"] as const;
export type AnswerLetter = (typeof ANSWER_LETTERS)[number];

export const MARKS_PER_OBJECTIVE_QUESTION = 2;
export const OBJECTIVE_MAX_SCORE =
  OBJECTIVE_QUESTION_IDS.length * MARKS_PER_OBJECTIVE_QUESTION; // 40

// Manual scale reuses the established 1-10 per-question convention from the
// legacy scores table.
export const MANUAL_SCORE_MIN = 1;
export const MANUAL_SCORE_MAX = 10;
export const FINAL_MAX_SCORE = OBJECTIVE_MAX_SCORE + MANUAL_SCORE_MAX * 2; // 60

// Legacy final scores are out of 80 and flagged below 50. The same 62.5%
// cut-off is applied to the objective model so flags stay comparable.
export const LEGACY_MAX_SCORE = 80;
export const LEGACY_FLAG_THRESHOLD = 50;
export const OBJECTIVE_FLAG_THRESHOLD =
  (LEGACY_FLAG_THRESHOLD / LEGACY_MAX_SCORE) * FINAL_MAX_SCORE; // 37.5

export function answerColumn(id: ObjectiveQuestionId): ObjectiveAnswerColumn {
  return `${id}_answer`;
}

export type ObjectiveQuestion = {
  id: ObjectiveQuestionId;
  title: string;
  options: Record<AnswerLetter, string>;
};

export const OBJECTIVE_QUESTIONS: readonly ObjectiveQuestion[] = [
  {
    id: "q1",
    title: "What is the main purpose of giving context in an AI prompt?",
    options: {
      A: "Make the prompt longer",
      B: "Help the AI understand the task and produce a relevant response",
      C: "Increase the AI's processing speed",
      D: "Remove the need to review the output",
    },
  },
  {
    id: "q2",
    title: "Which prompt is generally more effective?",
    options: {
      A: "“Write something about sales.”",
      B: "“Sales report.”",
      C: "“Analyze these sales results and identify the top 3 trends. Present the findings in a table.”",
      D: "“Give me sales information.”",
    },
  },
  {
    id: "q3",
    title: "What is the purpose of specifying the desired output format in a prompt?",
    options: {
      A: "To reduce the AI's intelligence",
      B: "To guide the AI on how the response should be structured",
      C: "To make the AI process information faster",
      D: "To prevent the AI from using context",
    },
  },
  {
    id: "q4",
    title: "What is prompt iteration?",
    options: {
      A: "Using the same prompt without changing it",
      B: "Improving a prompt based on the quality of the previous response",
      C: "Using several AI accounts at the same time",
      D: "Deleting previous prompts",
    },
  },
  {
    id: "q5",
    title: "What is a hallucination in generative AI?",
    options: {
      A: "When AI generates an image",
      B: "When AI produces information that is false or unsupported as if it were factual",
      C: "When AI stops responding",
      D: "When AI refuses a request",
    },
  },
  {
    id: "q6",
    title:
      "What should you generally do before using an important factual claim generated by AI?",
    options: {
      A: "Use it if it sounds convincing",
      B: "Ask AI the same question three times",
      C: "Verify it using reliable information or sources",
      D: "Assume newer AI models are always correct",
    },
  },
  {
    id: "q7",
    title: "Why are examples useful in an AI prompt?",
    options: {
      A: "They increase the processing speed",
      B: "They show the AI the expected format, style or pattern",
      C: "They guarantee a correct answer",
      D: "They remove the need for instructions",
    },
  },
  {
    id: "q8",
    title: "What is multimodal AI?",
    options: {
      A: "AI that can only process text",
      B: "AI that can work with different types of inputs such as text, images, audio or video",
      C: "AI that requires multiple computers",
      D: "AI that produces multiple answers",
    },
  },
  {
    id: "q9",
    title: "Which technology is primarily associated with AI-assisted coding?",
    options: {
      A: "GitHub Copilot",
      B: "Google Calendar",
      C: "Dropbox",
      D: "Trello",
    },
  },
  {
    id: "q10",
    title: "Which tool is primarily known for AI-powered image generation?",
    options: {
      A: "Midjourney",
      B: "Slack",
      C: "Google Sheets",
      D: "Jira",
    },
  },
  {
    id: "q11",
    title: "Which of the following is an example of generative AI?",
    options: {
      A: "An AI system generating a written report from a prompt",
      B: "A calculator performing 25 × 10",
      C: "A hard disk storing a file",
      D: "A printer printing a document",
    },
  },
  {
    id: "q12",
    title: "What is one major advantage of connecting AI with other software?",
    options: {
      A: "AI becomes automatically correct",
      B: "AI can work with information and perform actions as part of a workflow",
      C: "Human review becomes unnecessary",
      D: "Every task becomes fully automatic",
    },
  },
  {
    id: "q13",
    title: "What is an AI agent generally designed to do?",
    options: {
      A: "Only generate text",
      B: "Complete multiple steps toward a goal using available tools or actions",
      C: "Only answer predefined questions",
      D: "Replace every human decision",
    },
  },
  {
    id: "q14",
    title: "Which approach generally produces better results when asking AI to analyze data?",
    options: {
      A: "Give no objective and ask AI to find “everything important”",
      B: "Provide the data, explain the objective and specify the required output",
      C: "Ask AI to invent missing data",
      D: "Provide random pieces of information",
    },
  },
  {
    id: "q15",
    title: "Which statement about AI-generated content is correct?",
    options: {
      A: "AI-generated content is always accurate",
      B: "AI output never requires editing",
      C: "AI output should be reviewed for accuracy and relevance",
      D: "AI can guarantee that every statement is factual",
    },
  },
  {
    id: "q16",
    title:
      "What is the main purpose of giving an AI tool access to relevant documents or information?",
    options: {
      A: "To increase the length of its responses",
      B: "To help it generate responses based on the provided information",
      C: "To make the AI automatically correct",
      D: "To eliminate the need for prompts",
    },
  },
  {
    id: "q17",
    title: "Which is an example of AI automation?",
    options: {
      A: "Asking AI a single question",
      B: "Manually copying an AI response into another application",
      C: "Automatically summarizing incoming information and sending the summary to a designated channel",
      D: "Reading an AI-generated article",
    },
  },
  {
    id: "q18",
    title: "What is the main purpose of an AI workflow?",
    options: {
      A: "To use as many AI tools as possible",
      B: "To organize AI and other tools into a repeatable process for completing a task",
      C: "To eliminate all human involvement",
      D: "To generate longer AI responses",
    },
  },
  {
    id: "q19",
    title:
      "If two AI tools provide different answers to an important question, what is the appropriate approach?",
    options: {
      A: "Choose the longer answer",
      B: "Choose the more popular AI tool",
      C: "Verify the information using reliable sources or underlying data",
      D: "Combine both answers and assume they are correct",
    },
  },
  {
    id: "q20",
    title: "Which statement best describes effective AI usage?",
    options: {
      A: "Using the maximum number of AI tools",
      B: "Using AI for every possible task",
      C: "Choosing the appropriate AI tool, giving clear instructions and reviewing the output",
      D: "Accepting AI output without checking it",
    },
  },
];

export const Q21_QUESTION =
  "Which AI tools have you used or seriously explored this month?";
export const Q21_OTHER_PROMPT = "Which other AI tool(s) did you use or explore?";

export const Q21_TOOL_OPTIONS = [
  "ChatGPT",
  "Claude",
  "Gemini",
  "Microsoft Copilot",
  "Perplexity",
  "NotebookLM",
  "Grok",
  "DeepSeek",
  "Meta AI",
  "Google AI Studio",
  "Canva AI",
  "Midjourney",
  "Adobe Firefly",
  "Gamma",
  "Cursor",
  "GitHub Copilot",
  "Claude Code",
  "OpenAI Codex",
  "Replit",
  "Lovable",
  "Bolt",
  "v0",
  "Runway",
  "Kling AI",
  "ElevenLabs",
  "Suno",
  "Notion AI",
  "Zapier AI",
  "Make",
  "n8n",
  "Other",
] as const;

export type Q21Tool = (typeof Q21_TOOL_OPTIONS)[number];
export const Q21_OTHER_OPTION: Q21Tool = "Other";

export const Q22_QUESTION =
  "Share one example of AI-assisted work you completed this month.";
